### ISSUE TITLE
add privacy policy

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-ontology#2]
this cannot be hardcoded in the system, but needs to be configurable to allow future updates. At a given moment there can only be a single data use agreement. I suggest to store that here, and to keep old copies here as well for reference (although the CMS does not use them).

**Comment by robertoostenveld** [comment]
@hurngchunlee can you file a user story about updating the privacy policy?

**Comment by robertoostenveld** [comment]
I have added the current proposal for the privacy policy. 

mac011> git push
X11 forwarding request failed on channel 0
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (8/8), 2.59 KiB | 0 bytes/s, done.
Total 8 (delta 2), reused 0 (delta 0)
To git@github.com:donders-research-data-management/rdm-ontology.git
   9d72cf1..3252ae5  master -> master

**Comment by hurngchunlee** [comment]
I have added a new user story: https://radboud.atlassian.net/browse/RDM-599

"As a contributor or manager, I want to specify a Data Use Agreement that is not on the given list of DUA's".

**Comment by robertoostenveld** [comment]
This can be closed as this is now in Jira.
