### ISSUE TITLE
we need to add this one to the list of ethics review boards

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-ontology#3]
Ethics Assessment Committee Humanities
http://www.ru.nl/eac-humanities/
it should be in the popular ones, and I suggest to label it as EACH (like we have ECSW).

**Comment by hurngchunlee** [comment]
Updated as commit: https://github.com/donders-research-data-management/rdm-ontology/commit/f3b9bae4407c7a35ca411fa000a93a65f6004d72

**Comment by robertoostenveld** [comment]
I also just documented it in the ethics.md in rdm-wiki
